### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Spidious** [keifufu/WebNowPlaying-Redux-Rainmeter#11]
I have no idea how to install this. Some people on Reddit said to "Just install the example skin" and that did nothing. I cannot find any other instructions on what I'm supposed to do.

**Comment by keifufu** [comment]
That's all you have to do though. This is a plugin. The plugin will be installed with the example skin. You can then display the example skin by loading it in Rainmeter and other Rainmeter skins can use the plugin.
Any other questions?
