### ISSUE TITLE
Volume control breaks at 0%

### ISSUE THREAD

**Issue by p4rty4nimAl** [keifufu/WebNowPlaying-Redux-Rainmeter#12]
When using the template skin and Spotify, setting the volume to 0% will instead cause the skin to show the volume as 100%, at which point the volume controls on the skin cease to work. Other things, such as play/pause, continue to work and control Spotify, though.

I believe the following line may be the issue, after a quick glance.
https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/blob/437d1944e3a6c1433a61bcea198a4525da8da0ba/src/WNPReduxAdapterLibrary/WNPRedux.cs#L166

**Comment by keifufu** [comment]
Before looking into this i want to make sure you're using Spotify web and not the desktop player, right?

**Comment by p4rty4nimAl** [comment]
I am using the desktop player, with Spicetify and the associated plugin, if that changes anything.

**Comment by keifufu** [comment]
The Spicetify extension is no longer maintained as WebNowPlaying >2.0.0 can read from desktop players without it. The windows API used for this doesn't allow controlling volume and rating though.

**Comment by p4rty4nimAl** [comment]
I see, this issue would be with the extension rather than here if it were not deprecated. I have just tried to replicate the issue with the web player and it works fine, sorry!

**Comment by keifufu** [comment]
All good. I'd personally recommend not using Spotify but that's biased.
If you're using a Chromium based browser you can make Spotify web a PWA, so it'd feel more like a desktop app.
