### ISSUE TITLE
Webnowplaying drastically slowing down my PC

### ISSUE THREAD

**Issue by Agrasus** [keifufu/WebNowPlaying-Redux-Rainmeter#15]
I've been using Rainmeter with WNP for a long time. Recently i downloaded the Redux version after the old one has stopped working. But yesterday it started drastically slowing down my PC when i'm on the desktop. This issue appears even when there is no music playing. I have the newest version of Spicetify & Rainmeter. I even reinstalled rainmeter today and the issue still appears. Any ideas how to fix this? The Redux version also wasn't perfect and wasn't displaying everything correctly

**Comment by keifufu** [comment]
Sounds like it's the skins fault rather than WebNowPlaying. Either way, try restarting your computer, otherwise check your Rainmeter logs.
Spicetify is also not supported anymore. If you use a plugin >2.0.0 it'll automatically grab info from Spotify if you're on Windows 10 or 11.

**Comment by Agrasus** [comment]
Thank you for the fast response, it turns out it wasn't WNP but the Wallpaper Engine. Also, what do you mean Spicetify is not supported anymore? What plugin should i use for Spicetify then?

**Comment by keifufu** [comment]
I see, I'm glad it wasn't WebNowPlaying :3

As for Spicetify, Spicetify itself is of course still supported and in active development, the webnowplaying.js extension however is not needed anymore to get Spotify info into WebNowPlaying if you use the latest versions of the plugin. The only requirements are that you're on Windows 10 or 11, and have "Shoe desktop overlay when using media keys" enabled in the Spotify settings.
