### ISSUE TITLE
Tidal issues

### ISSUE THREAD

**Issue by dettlafferetein** [keifufu/WebNowPlaying-Redux-Rainmeter#3]
I encountered some problems when trying to get data from Tidal native player.

Position - Doesn't reset between songs, continuously builds up. Rewinding the song in either direction still keeps the timer at what it is. Refreshing rainmeter doesn't reset the timer either.

Duration - always 0:00.

Progress - is always at 100 (assuming because of duration always at 0:00).

Album name is also absent, but not a big issue.

I have no experience in C#, but I'll mess around with the code in my free time and see if I can find the source of the problem.

**Comment by keifufu** [comment]
I believe Tidal doesn't report this information to Windows, I'm sorry. This is something Tidal has to implement.

The position continuously building up is a bug though, it should be stuck at 0:00 if players don't report it.

**Comment by dettlafferetein** [comment]
> The position continuously building up is a bug though, it should be stuck at 0:00 if players don't report it.

Position doesn't build up when you pause, only when you play.

**Comment by keifufu** [comment]
Yup I'm aware
