### ISSUE TITLE
Tidal Destkop Image Resolution in Rainmeter and time of song....

### ISSUE THREAD

**Issue by Mojas84** [keifufu/WebNowPlaying-Redux-Rainmeter#32]
Hi. Please we can better fix it support for tidal destkop player?? Image is blur... And time of song not work.... 
![obrazek](https://github.com/user-attachments/assets/18ae94ce-75ca-41f6-bc4d-b707d770e3db)

**Comment by keifufu** [comment]
This is on Tidal.
