### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by PierrunoYT** [keifufu/WebNowPlaying-Redux-Rainmeter#6]
How do I install it?

**Comment by keifufu** [comment]
[Releases](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases)

**Comment by PierrunoYT** [comment]
Do I only need to Install the Rainmeter Skin?

**Comment by keifufu** [comment]
All skins that support webnowplaying already come bundled with it (although mostly older versions). To install new versions just download the .rmskin from releases and install it like any other skin, it will install the updated plugin with it.

**Comment by PierrunoYT** [comment]
Okay thank you and how can I use it for my own Rainmeter Skin?

**Comment by keifufu** [comment]
The .rmskin includes an example skin you can refer to, otherwise the Readme in this repo has the documentation for all the measures and bangs
