### ISSUE TITLE
Artist Attribute does not show multiple artists on Spotify

### ISSUE THREAD

**Issue by KrazyManJ** [keifufu/WebNowPlaying-Redux-Rainmeter#7]
When i try to get artist value from song with multiple artists while using spotify desktop version, it returns only first one but not all of them.

**Detail info**:
- Plugin version: `v2.0.5`
- Rainmeter version: `4.5.17.3600 (64-bit)`
- Operating System: Windows 11 Home

**Comment by keifufu** [comment]
Known issue, nothing I can do about it.
Spotify has decided to only return one artist.
