### ISSUE TITLE
Song rating not working

### ISSUE THREAD

**Issue by Rekushia** [keifufu/WebNowPlaying-Redux-Rainmeter#9]
Hi, i've noticed that the song rating funtion doesn't seem to work. It neither shows the current rating, nor can you change it with !ToggleThumbsUp/Down and !SetRating. Rainmeter also shows that the range for the MeasureRating is from 0 to 1.

I've also encountered another problem. I'm not sure if i should describe it here or create a new issue, but it's regarding the album art.

**Comment by keifufu** [comment]
With what player? Also describe the album art issue here.

**Comment by Rekushia** [comment]
I've tested it with spotify/spicetify and tidal player, and youtube website.

Regarding the album art issue. When having 2 players "open", the album art doesn't switch properly. For example, when i watch something on youtube, the thumbnail shows properly, but if i pause, and play something on spotify, the thumbnail still shows that youtube video (and vice versa). Title, artist and other playback info and controls work fine.

**Comment by keifufu** [comment]
> Also, the skin remembers the last image it used, and displays that even after refresh or pc restart, but i guess that could be solved by removing the content of the WNP temp folder on initial launch.

For native players I think so, yes.

**Comment by Rekushia** [comment]
> I'll see about the album art issue once I have some time to debug it. As for rating, native players (Spotify Desktop, Tidal) don't support rating, only websites do.

See, this is weird, as it worked for me last week. I might've used a different version of the WNP plugin i guess?. It stopped working when i installed the WNP browser extension and it prompted me to update the plugin.

**Comment by keifufu** [comment]
> > I'll see about the album art issue once I have some time to debug it. As for rating, native players (Spotify Desktop, Tidal) don't support rating, only websites do.
> 
> See, this is weird, as it worked for me last week. I might've used a different version of the WNP plugin i guess?. It stopped working when i installed the WNP browser extension and it prompted me to update the plugin.

Spicetify is not supported as of right now. With WNP 2.0.0 and newer, native players are supported out of the box, however due to the Windows API it's impossible to interact with rating and volume.

I honestly recommend using web players if you're someone to have a browser open all the time anyway.

**Comment by Rekushia** [comment]
I've just checked, the rating doesn't seem to work on spotify web player either.

**Comment by keifufu** [comment]
> I've just checked, the rating doesn't seem to work on spotify web player either.

It should be able to read it but not change it. Spotify changed their css (as they do every 7 minutes) which broke it (I haven't bothered to update the extension yet)

**Comment by Rekushia** [comment]
Unfortunately, it doesn't seem to be able to read it as well. Ehh, it's not like it's a killer, but a "nice to have" thing. For now i'll just hide the like dislike icons from my skin. And thanks for looking into the album art problem. It doesn't seem to be an issue when using the web player, so i'll just use that.

**Comment by lehuymanhtan** [comment]
> > I'll see about the album art issue once I have some time to debug it. As for rating, native players (Spotify Desktop, Tidal) don't support rating, only websites do.
> 
> See, this is weird, as it worked for me last week. I might've used a different version of the WNP plugin i guess?. It stopped working when i installed the WNP browser extension and it prompted me to update the plugin.

The reason is that the wnp extension comes with Spicetify only supports WNP version below 2.0.0. 
So if you still want song rating, you can install the extension called [WebNowPlaying-Redux-Spicetify](https://github.com/keifufu/WebNowPlaying-Redux-Spicetify) from Spicetify-Marketplace. it should work. even now it's deprecated but it still supports WNP version 2.x.x.

**Comment by keifufu** [comment]
What? No it doesn't.

**Comment by lehuymanhtan** [comment]
> What? No it doesn't.

ok. It doesn't work if native API is turned on, but it did work if native API is turned off.

![image](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/assets/81731577/492059b8-5131-4a56-81d0-394f57c1acc6)

**Comment by keifufu** [comment]
Alright, well I don't recommend it.

**Comment by keifufu** [comment]
Spotify web rating has been fixed by now.
If you're using a chromium based browser you can install the web player as a PWA app, to make it feel more like a desktop app if that's what you want.
